[package]
name = "plan9sys"
version = "0.1.0"
authors = ["Stefan Hertenberger <stefan@alarum.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
